name: Complete Workflow

on:
  push:
    branches:
      - main
      - master
      - deploy
  pull_request:
    branches:
      - main
      - master
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.2]

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run all tests
      run: yarn test

    - name: Deployment
      if: github.ref == 'refs/heads/deploy'
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "my-app-name"
        heroku_email: "my-email@domain.com"
        buildpack: "https://github.com/zidizei/heroku-buildpack-tsc#v2.0"
